# Generated by Django 5.0.7 on 2024-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='todos',
            name='content',
            field=models.CharField(max_length=700),
        ),
    ]
